// Generated by `wit-bindgen` 0.11.0. DO NOT EDIT!
#include "the_world.h"


__attribute__((__import_module__("foo:foo/integers"), __import_name__("a1")))
void __wasm_import_foo_foo_integers_a1(int32_t);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("a2")))
void __wasm_import_foo_foo_integers_a2(int32_t);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("a3")))
void __wasm_import_foo_foo_integers_a3(int32_t);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("a4")))
void __wasm_import_foo_foo_integers_a4(int32_t);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("a5")))
void __wasm_import_foo_foo_integers_a5(int32_t);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("a6")))
void __wasm_import_foo_foo_integers_a6(int32_t);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("a7")))
void __wasm_import_foo_foo_integers_a7(int64_t);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("a8")))
void __wasm_import_foo_foo_integers_a8(int64_t);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("a9")))
void __wasm_import_foo_foo_integers_a9(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int64_t, int64_t);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("r1")))
int32_t __wasm_import_foo_foo_integers_r1(void);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("r2")))
int32_t __wasm_import_foo_foo_integers_r2(void);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("r3")))
int32_t __wasm_import_foo_foo_integers_r3(void);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("r4")))
int32_t __wasm_import_foo_foo_integers_r4(void);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("r5")))
int32_t __wasm_import_foo_foo_integers_r5(void);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("r6")))
int32_t __wasm_import_foo_foo_integers_r6(void);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("r7")))
int64_t __wasm_import_foo_foo_integers_r7(void);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("r8")))
int64_t __wasm_import_foo_foo_integers_r8(void);

__attribute__((__import_module__("foo:foo/integers"), __import_name__("pair-ret")))
void __wasm_import_foo_foo_integers_pair_ret(int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Component Adapters

__attribute__((__aligned__(8)))
static uint8_t RET_AREA[16];

void foo_foo_integers_a1(uint8_t x) {
  __wasm_import_foo_foo_integers_a1((int32_t) (x));
}

void foo_foo_integers_a2(int8_t x) {
  __wasm_import_foo_foo_integers_a2((int32_t) (x));
}

void foo_foo_integers_a3(uint16_t x) {
  __wasm_import_foo_foo_integers_a3((int32_t) (x));
}

void foo_foo_integers_a4(int16_t x) {
  __wasm_import_foo_foo_integers_a4((int32_t) (x));
}

void foo_foo_integers_a5(uint32_t x) {
  __wasm_import_foo_foo_integers_a5((int32_t) (x));
}

void foo_foo_integers_a6(int32_t x) {
  __wasm_import_foo_foo_integers_a6(x);
}

void foo_foo_integers_a7(uint64_t x) {
  __wasm_import_foo_foo_integers_a7((int64_t) (x));
}

void foo_foo_integers_a8(int64_t x) {
  __wasm_import_foo_foo_integers_a8(x);
}

void foo_foo_integers_a9(uint8_t p1, int8_t p2, uint16_t p3, int16_t p4, uint32_t p5, int32_t p6, uint64_t p7, int64_t p8) {
  __wasm_import_foo_foo_integers_a9((int32_t) (p1), (int32_t) (p2), (int32_t) (p3), (int32_t) (p4), (int32_t) (p5), p6, (int64_t) (p7), p8);
}

uint8_t foo_foo_integers_r1(void) {
  int32_t ret = __wasm_import_foo_foo_integers_r1();
  return (uint8_t) (ret);
}

int8_t foo_foo_integers_r2(void) {
  int32_t ret = __wasm_import_foo_foo_integers_r2();
  return (int8_t) (ret);
}

uint16_t foo_foo_integers_r3(void) {
  int32_t ret = __wasm_import_foo_foo_integers_r3();
  return (uint16_t) (ret);
}

int16_t foo_foo_integers_r4(void) {
  int32_t ret = __wasm_import_foo_foo_integers_r4();
  return (int16_t) (ret);
}

uint32_t foo_foo_integers_r5(void) {
  int32_t ret = __wasm_import_foo_foo_integers_r5();
  return (uint32_t) (ret);
}

int32_t foo_foo_integers_r6(void) {
  int32_t ret = __wasm_import_foo_foo_integers_r6();
  return ret;
}

uint64_t foo_foo_integers_r7(void) {
  int64_t ret = __wasm_import_foo_foo_integers_r7();
  return (uint64_t) (ret);
}

int64_t foo_foo_integers_r8(void) {
  int64_t ret = __wasm_import_foo_foo_integers_r8();
  return ret;
}

void foo_foo_integers_pair_ret(the_world_tuple2_s64_u8_t *ret) {
  __attribute__((__aligned__(8)))
  uint8_t ret_area[16];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_foo_foo_integers_pair_ret(ptr);
  *ret = (the_world_tuple2_s64_u8_t) {
    *((int64_t*) (ptr + 0)),
    (uint8_t) ((int32_t) (*((uint8_t*) (ptr + 8)))),
  };
}

__attribute__((__export_name__("foo:foo/integers#a1")))
void __wasm_export_exports_foo_foo_integers_a1(int32_t arg) {
  exports_foo_foo_integers_a1((uint8_t) (arg));
}

__attribute__((__export_name__("foo:foo/integers#a2")))
void __wasm_export_exports_foo_foo_integers_a2(int32_t arg) {
  exports_foo_foo_integers_a2((int8_t) (arg));
}

__attribute__((__export_name__("foo:foo/integers#a3")))
void __wasm_export_exports_foo_foo_integers_a3(int32_t arg) {
  exports_foo_foo_integers_a3((uint16_t) (arg));
}

__attribute__((__export_name__("foo:foo/integers#a4")))
void __wasm_export_exports_foo_foo_integers_a4(int32_t arg) {
  exports_foo_foo_integers_a4((int16_t) (arg));
}

__attribute__((__export_name__("foo:foo/integers#a5")))
void __wasm_export_exports_foo_foo_integers_a5(int32_t arg) {
  exports_foo_foo_integers_a5((uint32_t) (arg));
}

__attribute__((__export_name__("foo:foo/integers#a6")))
void __wasm_export_exports_foo_foo_integers_a6(int32_t arg) {
  exports_foo_foo_integers_a6(arg);
}

__attribute__((__export_name__("foo:foo/integers#a7")))
void __wasm_export_exports_foo_foo_integers_a7(int64_t arg) {
  exports_foo_foo_integers_a7((uint64_t) (arg));
}

__attribute__((__export_name__("foo:foo/integers#a8")))
void __wasm_export_exports_foo_foo_integers_a8(int64_t arg) {
  exports_foo_foo_integers_a8(arg);
}

__attribute__((__export_name__("foo:foo/integers#a9")))
void __wasm_export_exports_foo_foo_integers_a9(int32_t arg, int32_t arg0, int32_t arg1, int32_t arg2, int32_t arg3, int32_t arg4, int64_t arg5, int64_t arg6) {
  exports_foo_foo_integers_a9((uint8_t) (arg), (int8_t) (arg0), (uint16_t) (arg1), (int16_t) (arg2), (uint32_t) (arg3), arg4, (uint64_t) (arg5), arg6);
}

__attribute__((__export_name__("foo:foo/integers#r1")))
int32_t __wasm_export_exports_foo_foo_integers_r1(void) {
  uint8_t ret = exports_foo_foo_integers_r1();
  return (int32_t) (ret);
}

__attribute__((__export_name__("foo:foo/integers#r2")))
int32_t __wasm_export_exports_foo_foo_integers_r2(void) {
  int8_t ret = exports_foo_foo_integers_r2();
  return (int32_t) (ret);
}

__attribute__((__export_name__("foo:foo/integers#r3")))
int32_t __wasm_export_exports_foo_foo_integers_r3(void) {
  uint16_t ret = exports_foo_foo_integers_r3();
  return (int32_t) (ret);
}

__attribute__((__export_name__("foo:foo/integers#r4")))
int32_t __wasm_export_exports_foo_foo_integers_r4(void) {
  int16_t ret = exports_foo_foo_integers_r4();
  return (int32_t) (ret);
}

__attribute__((__export_name__("foo:foo/integers#r5")))
int32_t __wasm_export_exports_foo_foo_integers_r5(void) {
  uint32_t ret = exports_foo_foo_integers_r5();
  return (int32_t) (ret);
}

__attribute__((__export_name__("foo:foo/integers#r6")))
int32_t __wasm_export_exports_foo_foo_integers_r6(void) {
  int32_t ret = exports_foo_foo_integers_r6();
  return ret;
}

__attribute__((__export_name__("foo:foo/integers#r7")))
int64_t __wasm_export_exports_foo_foo_integers_r7(void) {
  uint64_t ret = exports_foo_foo_integers_r7();
  return (int64_t) (ret);
}

__attribute__((__export_name__("foo:foo/integers#r8")))
int64_t __wasm_export_exports_foo_foo_integers_r8(void) {
  int64_t ret = exports_foo_foo_integers_r8();
  return ret;
}

__attribute__((__export_name__("foo:foo/integers#pair-ret")))
int32_t __wasm_export_exports_foo_foo_integers_pair_ret(void) {
  the_world_tuple2_s64_u8_t ret;
  exports_foo_foo_integers_pair_ret(&ret);
  int32_t ptr = (int32_t) &RET_AREA;
  *((int64_t*)(ptr + 0)) = (ret).f0;
  *((int8_t*)(ptr + 8)) = (int32_t) ((ret).f1);
  return ptr;
}

extern void __component_type_object_force_link_the_world(void);
void __component_type_object_force_link_the_world_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_the_world();
}
