// Generated by `wit-bindgen` 0.11.0. DO NOT EDIT!
#ifndef __BINDINGS_THE_WORLD_H
#define __BINDINGS_THE_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  int64_t f0;
  uint8_t f1;
} the_world_tuple2_s64_u8_t;

// Imported Functions from `foo:foo/integers`
void foo_foo_integers_a1(uint8_t x);
void foo_foo_integers_a2(int8_t x);
void foo_foo_integers_a3(uint16_t x);
void foo_foo_integers_a4(int16_t x);
void foo_foo_integers_a5(uint32_t x);
void foo_foo_integers_a6(int32_t x);
void foo_foo_integers_a7(uint64_t x);
void foo_foo_integers_a8(int64_t x);
void foo_foo_integers_a9(uint8_t p1, int8_t p2, uint16_t p3, int16_t p4, uint32_t p5, int32_t p6, uint64_t p7, int64_t p8);
uint8_t foo_foo_integers_r1(void);
int8_t foo_foo_integers_r2(void);
uint16_t foo_foo_integers_r3(void);
int16_t foo_foo_integers_r4(void);
uint32_t foo_foo_integers_r5(void);
int32_t foo_foo_integers_r6(void);
uint64_t foo_foo_integers_r7(void);
int64_t foo_foo_integers_r8(void);
void foo_foo_integers_pair_ret(the_world_tuple2_s64_u8_t *ret);

// Exported Functions from `foo:foo/integers`
void exports_foo_foo_integers_a1(uint8_t x);
void exports_foo_foo_integers_a2(int8_t x);
void exports_foo_foo_integers_a3(uint16_t x);
void exports_foo_foo_integers_a4(int16_t x);
void exports_foo_foo_integers_a5(uint32_t x);
void exports_foo_foo_integers_a6(int32_t x);
void exports_foo_foo_integers_a7(uint64_t x);
void exports_foo_foo_integers_a8(int64_t x);
void exports_foo_foo_integers_a9(uint8_t p1, int8_t p2, uint16_t p3, int16_t p4, uint32_t p5, int32_t p6, uint64_t p7, int64_t p8);
uint8_t exports_foo_foo_integers_r1(void);
int8_t exports_foo_foo_integers_r2(void);
uint16_t exports_foo_foo_integers_r3(void);
int16_t exports_foo_foo_integers_r4(void);
uint32_t exports_foo_foo_integers_r5(void);
int32_t exports_foo_foo_integers_r6(void);
uint64_t exports_foo_foo_integers_r7(void);
int64_t exports_foo_foo_integers_r8(void);
void exports_foo_foo_integers_pair_ret(the_world_tuple2_s64_u8_t *ret);

#ifdef __cplusplus
}
#endif
#endif
