// Generated by `wit-bindgen` 0.11.0. DO NOT EDIT!
#ifndef __BINDINGS_ADDER_H
#define __BINDINGS_ADDER_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>

// Exported Functions from `docs:calculator/add@0.1.0`
uint32_t exports_docs_calculator_add_add(uint32_t a, uint32_t b);

#ifdef __cplusplus
}
#endif
#endif
